/**
 * Task Model - MongoDB/Mongoose Schema
 * ======================================
 * 
 * ARCHITECTURAL DECISION: Why Mongoose instead of raw MongoDB driver?
 * 
 * Mongoose provides:
 * 1. Schema validation at the application layer (fail-fast before DB writes)
 * 2. Middleware hooks for pre/post operations (great for logging/audit trails)
 * 3. TypeScript support with strict schemas
 * 4. Populate functionality for relational lookups without joins
 * 
 * INTERVIEW ANSWER: In production, we want validation errors caught early 
 * (in TypeScript runtime) rather than late (in MongoDB query failures).
 */

import mongoose, { Schema, Document, Model } from 'mongoose';

// ============================================================================
// PHASE 1A: Define TypeScript Interfaces FIRST (before Schema)
// ============================================================================
// Why? Because Schema.Types can't reference 'string' - we must use Schema.Types.String
// But our interface is purely for TypeScript, enabling IDE autocomplete and null checks.

/**
 * Individual subtask breakdown generated by AI
 * complexityEstimation: AI evaluates task difficulty for sprint planning
 * status: Tracks completion of each subtask independently
 */
export interface ISubtask {
  title: string;
  complexityEstimation: 'low' | 'medium' | 'high';
  status: 'pending' | 'done';
}

/**
 * Main Task document structure
 * Mirrors real-world enterprise requirements for task management systems
 */
export interface ITask extends Document {
  title: string;
  rawDescription: string;
  aiStatus: 'pending' | 'processing' | 'completed' | 'failed';
  automatedSubtasks: ISubtask[];
  userId: string;  // Multi-tenant: isolates each user's data (GDPR/privacy friendly)
  createdAt: Date;
  updatedAt: Date;
}

// ============================================================================
// PHASE 1B: Define Schema with Strict Type Safety
// ============================================================================

const SubtaskSchema = new Schema<ISubtask>(
  {
    // TITLE: Human-readable subtask name
    title: {
      type: String,
      required: [true, 'Subtask title is required'],
      trim: true,  // Strips whitespace - prevents "  Test" vs "Test" inconsistency
      maxlength: [200, 'Subtask title cannot exceed 200 characters']
    },
    // COMPLEXITY ESTIMATION: Enables sprint velocity calculations
    // low=1pt, medium=3pt, high=5pt (Fibonacci-like estimation)
    complexityEstimation: {
      type: String,
      enum: {
        values: ['low', 'medium', 'high'],
        message: 'Complexity must be: low, medium, or high'
      },
      required: true
    },
    // STATUS: Tracks individual subtask completion (not the whole task)
    status: {
      type: String,
      enum: {
        values: ['pending', 'done'],
        message: 'Status must be: pending or done'
      },
      default: 'pending'
    }
  },
  {
    _id: false  // No _id on subdocuments - MongoDB generates them if needed
  }
);

const TaskSchema = new Schema<ITask>(
  {
    // TITLE: Main task name - indexed for search functionality
    title: {
      type: String,
      required: [true, 'Task title is required'],
      trim: true,
      maxlength: [300, 'Title cannot exceed 300 characters']
    },
    
    // RAW DESCRIPTION: Original user input before AI processing
    // Stored for: audit trails, re-processing if AI fails, analytics on common patterns
    rawDescription: {
      type: String,
      required: [true, 'Task description is required'],
      maxlength: [10000, 'Description cannot exceed 10,000 characters']
    },
    
    // AI STATUS: Lifecycle tracking for async AI operations
    // pending → processing → completed/failed
    // Using explicit state machine prevents undefined states
    aiStatus: {
      type: String,
      enum: {
        values: ['pending', 'processing', 'completed', 'failed'],
        message: 'AI status must be: pending, processing, completed, or failed'
      },
      default: 'pending',
      index: true  // Single-field index for status-only queries
    },
    
    // AUTOMATED SUBTASKS: AI-generated breakdown stored inline
    // ARCHITECTURAL DECISION: Embedded array (not referenced collection)
    // Why? Subtasks are tightly coupled to parent task - no need for separate collection.
    // If subtasks were independent, we'd use mongoose.Schema.Types.ObjectId with ref:'Subtask'
    automatedSubtasks: [SubtaskSchema],
    
    // USER ID: Multi-tenant isolation key
    // CRITICAL: Every query MUST filter by userId to prevent data leakage
    userId: {
      type: String,
      required: [true, 'User ID is required for multi-tenant isolation'],
      index: true  // Indexed for user-specific queries
    }
  },
  {
    // TIMESTAMPS: Automatic createdAt/updatedAt without manual management
    // Mongoose handles updatedAt updates on every .save() call
    timestamps: true
  }
);

// ============================================================================
// PHASE 1C: Compound Index for Query Optimization
// ============================================================================

/**
 * COMPOUND INDEX: { userId: 1, aiStatus: 1 }
 * 
 * INTERVIEW ANSWER - Why this index matters:
 * 
 * SCENARIO: Frontend loads "My Active Processing Tasks" panel
 * QUERY: db.tasks.find({ userId: "user123", aiStatus: "processing" })
 * 
 * WITHOUT INDEX:
 * - MongoDB performs COLLSCAN (collection scan) - reads EVERY document
 * - For 1M tasks, this means 1M document reads + network round trips
 * - Response time: 2000ms+
 * 
 * WITH INDEX:
 * - MongoDB uses IXSCAN (index scan) - jumps directly to matching docs
 * - B-tree structure: O(log n) lookup instead of O(n) scan
 * - For 1M tasks, this means ~20 index lookups + minimal doc fetches
 * - Response time: 5-50ms
 * 
 * ARCHITECTURAL DECISION: Compound index order matters!
 * - userId comes FIRST because it's HIGH-CARDINALITY (more unique values)
 * - aiStatus comes SECOND (only 4 values)
 * - MongoDB can efficiently use the index for: 
 *   1. userId only (exact match)
 *   2. userId + aiStatus (compound)
 *   3. Range queries on userId
 */
TaskSchema.index({ userId: 1, aiStatus: 1 });

/**
 * ADDITIONAL INDEX: { createdAt: -1 }
 * 
 * Enables efficient "recent tasks" queries for dashboard loading
 * -1 = descending (newest first)
 */
TaskSchema.index({ createdAt: -1 });

// ============================================================================
// PHASE 1D: Schema Pre-save Hook (Optional but Production-Ready)
// ============================================================================

// Normalize userId to lowercase for case-insensitive lookups
// INTERVIEW POINT: Middleware demonstrates understanding of enterprise patterns
TaskSchema.pre('save', function (next) {
  // Only normalize if userId is a string (could be ObjectId in other projects)
  if (typeof this.userId === 'string') {
    this.userId = this.userId.toLowerCase().trim();
  }
  next();
});

// ============================================================================
// PHASE 1E: Instance Methods (Task-related business logic)
// ============================================================================

/**
 * Check if task has any pending subtasks
 * Used by frontend to determine if "All Done" badge should show
 */
TaskSchema.methods.hasPendingSubtasks = function (): boolean {
  return (this.automatedSubtasks as ISubtask[]).some(sub => sub.status === 'pending');
};

/**
 * Get completion percentage
 * Used by frontend progress bar
 */
TaskSchema.methods.getCompletionPercentage = function (): number {
  if (this.automatedSubtasks.length === 0) return 0;
  const subTasks = this.automatedSubtasks as ISubtask[];
  const completed = subTasks.filter(sub => sub.status === 'done').length;
  return Math.round((completed / this.automatedSubtasks.length) * 100);
};

// ============================================================================
// PHASE 1F: Export Model with Type Safety
// ============================================================================

// Model<MongoDB_Document_Type, Query_Helper_Type>
// Second generic param = "model type" for static methods
export const Task: Model<ITask> = mongoose.model<ITask>('Task', TaskSchema);

// ============================================================================
// BONUS: Index Performance Explanation for Interview
// ============================================================================
/*
RESOURCE ALLOCATION (Real-world impact):

Without compound index:
- Query time: O(n) - must scan all documents
- Memory: Loads entire collection into memory for filtering
- Connection pool: Holds connection longer, reducing concurrency
- At scale: Need more application servers to handle same load

With compound index:
- Query time: O(log n) - binary tree traversal
- Memory: Only index tree + matching documents
- Connection pool: Returns quickly, more concurrent users per server
- At scale: Same infrastructure handles 10x more users

REAL NUMBERS (approximate for 1M documents):
- COLLSCAN: 2000-5000ms
- IXSCAN (compound): 10-50ms
- Result: 100x performance improvement
*/